repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: python -m pytest tests
        language: system
        pass_filenames: false
        stages: [commit]
        types: [python]
      - id: black
        name: black
        entry: black app
        language: system
        types: [python]
        files: app/
      - id: pylint
        name: pylint
        entry: pylint
        args: [.pylintrc]
        language: system
        pass_filenames: true
        stages: [commit]
        types: [python]
        files: app/
